PERL_MAJOR_VER = 5.10

SPECIFIC_PACKAGES = \
	ipkg-opt \
	$(PACKAGES_REQUIRE_LINUX26) \

BROKEN_PACKAGES = \
	$(PACKAGES_ONLY_WORK_ON_LINUX24) \
	aget \
	bitchx \

ARIA2_PATCHES := $(SOURCE_DIR)/aria2/IPV6_V6ONLY-wdtv.patch

ALSA-OSS_CPPFLAGS:=-U_FILE_OFFSET_BITS


RTORRENT_VERSION := 0.8.2
RTORRENT_IPK_VERSION := 2
